Fix build of nptl/tst-thread_local1.cc with GCC 12
commit 803c959745fd7c679e00f9bad58822616f0e51cb
Author: Joseph Myers <joseph@codesourcery.com>
Date:   Mon Aug 2 16:33:44 2021 +0000

    Fix build of nptl/tst-thread_local1.cc with GCC 12

    The test nptl/tst-thread_local1.cc fails to build with GCC mainline
    because of changes to what libstdc++ headers implicitly include what
    other headers:

    tst-thread_local1.cc: In function 'int do_test()':
    tst-thread_local1.cc:177:5: error: variable 'std::array<std::pair<const char*, std::function<void(void* (*)(void*))> >, 2> do_thread_X' has initializer but incomplete type
      177 |     do_thread_X
          |     ^~~~~~~~~~~

    Fix this by adding an explicit include of <array>.

    Tested with build-many-glibcs.py for aarch64-linux-gnu.

    (cherry picked from commit 2ee9b24f47db8d0a8d0ccadb999335a1d4cfc364)