hppa: Implement swapcontext in assembler (bug 28960)
commit 738ee53f0ce5e39b9b7a6777f5d3057afbaac498
Author: John David Anglin <danglin@gcc.gnu.org>
Date:   Tue Mar 15 23:12:37 2022 +0000

    hppa: Implement swapcontext in assembler (bug 28960)

    When swapcontext.c is compiled without -g, the following error occurs:
    Error: CFI instruction used without previous .cfi_startproc

    Fix by converting swapcontext routine to assembler.