string.h: fix __fortified_attr_access macro call [BZ #29162]
commit 14770f3e0462721b317f138197e1fbf4db542c94
Author: Sergei Trofimovich <slyich@gmail.com>
Date:   Mon May 23 13:56:43 2022 +0530

    string.h: fix __fortified_attr_access macro call [BZ #29162]

    commit e938c0274 "Don't add access size hints to fortifiable functions"
    converted a few '__attr_access ((...))' into '__fortified_attr_access (...)'
    calls.

    But one of conversions had double parentheses of '__fortified_attr_access (...)'.

    Noticed as a gnat6 build failure:

        /<<NIX>>-glibc-2.34-210-dev/include/bits/string_fortified.h:110:50: error: macro "__fortified_attr_access" requires 3 arguments, but only 1 given

    The change fixes parentheses.

    This is seen when using compilers that do not support
    __builtin___stpncpy_chk, e.g. gcc older than 4.7, clang older than 2.6
    or some compiler not derived from gcc or clang.

    Signed-off-by: Sergei Trofimovich <slyich@gmail.com>
    Reviewed-by: Siddhesh Poyarekar <siddhesh@sourceware.org>
    (cherry picked from commit 5a5f94af0542f9a35aaa7992c18eb4e2403a29b9)